# -*- coding: utf-8 -*-
"""Exercise2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwqXENCSX2lM25DMF56JmXYwUe4bLGGB
"""

import tensorflow as tf
import numpy as np
celsius = np.array([-40,-10,0,8,15,22,38], dtype=float)
fahrenheit = np.array([-40,14,32,46,59,72,100], dtype = float)

oculta1= tf.keras.layers.Dense(units= 3, input_shape=[1])
oculta2 = tf.keras.layers.Dense(units= 3)
salida = tf.keras.layers.Dense(units = 1)

model = tf.keras.Sequential([oculta1, oculta2, salida])

model.compile(
    optimizer= tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)



print('the model is training...')
historial = model.fit(celsius, fahrenheit, epochs=1000, verbose=False)
print('Model is trained')

import matplotlib.pyplot as plt

plt.xlabel('# Iteration')
plt.ylabel('Magnitud de pérdida')

plt.plot(historial.history['loss'])

result = model.predict([100])
print("result is: " + str(result) + " fahrenheit")

print('model internal variables')
print(oculta1.get_weights())
print(oculta2.get_weights())
print(salida.get_weights())