# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYhYChyt21NvWA1bRrLFuQYWXpBjiBU3
"""

import tensorflow as tf
import numpy as np



celsius = np.array([-40,-10,0,8,15,22,38], dtype=float)
fahrenheit = np.array([-40,14,32,46,59,72,100], dtype = float)

capa = tf.keras.layers.Dense(units= 1, input_shape=[1])
model = tf.keras.Sequential([capa])

model.compile(
    optimizer= tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

"""now is time to train"""

print('the model is training...')
historial = model.fit(celsius, fahrenheit, epochs=1000, verbose=False)
print('Model is trained')

model.save('fahrenheit_to_celsius.h5')

!pip install tensorflowjs

!mkdir carpeta_salida
!tensorflowjs_converter --input_format keras fahrenheit_to_celsius.h5 carpeta_salida

!ls carpeta_salida

import matplotlib.pyplot as plt

plt.xlabel('# Iteration')
plt.ylabel('Magnitud de pérdida')

plt.plot(historial.history['loss'])

result = model.predict([100])
print("result is: " + str(result) + " fahrenheit")

print('model internal variables')
print(capa.get_weights())

"""F = C * 1.8 + 32"""